### ISSUE TITLE
Should `*` be converted to `[^/]*` instead of `[^/]+`

### ISSUE THREAD

**Issue by czuniga9** [timoschinkel/codeowners#30]
I have a CODEOWNERS file with a pattern like  `**/*Foo**` to match any file with `Foo` in it. The `*` converted to `[^/]+` prevented it from working on files like `example/FooSomething`. I changed it to `[^/]*` and this worked for me, but I'm not sure if this would break other things.

Thanks for the great package btw!

**Comment by timoschinkel** [comment]
Hi, thanks for the issue. Please allow me some time to verify the suggestion.

**Comment by timoschinkel** [comment]
I've applied a fix and tagged version `2.2.1`.
